"""Email the judge's verdict report to an arbitrary address.

Self-serve by design: anyone who forks this repository can add two
secrets (SMTP_USER / SMTP_PASS), pass an address to the workflow, and
get the report in their inbox. No account here, no shared relay, no
dependency on the repository owner's infrastructure.

Configuration comes from the environment only - nothing is ever written
back to disk or committed:

    SMTP_HOST   default smtp.gmail.com
    SMTP_PORT   default 587 (STARTTLS); 465 switches to implicit TLS
    SMTP_USER   the mailbox to send from (required)
    SMTP_PASS   password or app-password (required)
    SMTP_FROM   From: header, defaults to SMTP_USER

Gmail needs an app password (a normal account password is rejected):
Google Account -> Security -> 2-Step Verification -> App passwords.

Nothing here raises. send_report() answers (ok, message) so the caller
can log a failure and still finish the run - a broken mailbox must never
lose an analysis that already cost minutes of compute.
"""
import os
import re
import smtplib
import ssl
from email.message import EmailMessage

# Deliberately permissive: this only guards against obvious typos and
# header injection, not against every address RFC 5321 permits.
_ADDR_RE = re.compile(r"^[^@\s,;:<>]+@[^@\s,;:<>]+\.[A-Za-z]{2,}$")

DEFAULT_HOST = "smtp.gmail.com"
DEFAULT_PORT = 587


class SMTPConfigError(RuntimeError):
    """Required SMTP settings are missing from the environment."""


def valid_address(addr):
    """True when `addr` looks like a single deliverable address.

    Newlines are rejected explicitly: an address carrying CR/LF could
    inject extra headers into the outgoing message.
    """
    if not isinstance(addr, str):
        return False
    addr = addr.strip()
    if not addr or "\n" in addr or "\r" in addr:
        return False
    return bool(_ADDR_RE.match(addr))


def smtp_settings(env=None):
    """Read SMTP settings from the environment.

    Raises SMTPConfigError when a required value is missing, so callers
    can tell "not configured" apart from "configured but failed".
    """
    env = os.environ if env is None else env
    user = (env.get("SMTP_USER") or "").strip()
    password = env.get("SMTP_PASS") or ""
    if not user or not password:
        missing = [name for name, val in (("SMTP_USER", user),
                                          ("SMTP_PASS", password)) if not val]
        raise SMTPConfigError(
            f"missing {' and '.join(missing)} - set them as repository "
            "secrets (or environment variables) to enable email delivery")
    try:
        port = int(env.get("SMTP_PORT") or DEFAULT_PORT)
    except (TypeError, ValueError):
        port = DEFAULT_PORT
    return {
        "host": (env.get("SMTP_HOST") or DEFAULT_HOST).strip(),
        "port": port,
        "user": user,
        "password": password,
        "sender": (env.get("SMTP_FROM") or user).strip(),
    }


# --------------------------------------------------------------------------
# Markdown -> HTML. The report is generated by judge_cli._render_markdown,
# so only the subset it actually emits needs handling: headings, tables,
# bullets, blockquotes, inline code and bold. A full markdown engine would
# be a dependency for no gain.
# --------------------------------------------------------------------------
def _escape(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;"))


# Severity words get a color wherever the report bolds them or puts them
# alone in a table cell. Inline styles (not classes): the same HTML is an
# email body, a browser page and the weasyprint PDF source, and inline is
# the only styling all three honor. DE-ESCALATED before ESCALATED so the
# alternation cannot half-match the hyphenated form.
_SEVERITY_COLORS = {
    "malicious": "#cf222e", "MALICIOUS": "#cf222e",
    "suspicious": "#9a6700", "SUSPICIOUS": "#9a6700",
    "benign": "#1a7f37", "BENIGN": "#1a7f37",
    "DE-ESCALATED": "#1a7f37", "ESCALATED": "#cf222e",
    "STABLE": "#1a7f37", "MIXED": "#9a6700",
}
_SEVERITY_RE = re.compile(
    r"\b(DE-ESCALATED|ESCALATED|STABLE|MIXED|"
    r"malicious|suspicious|benign|MALICIOUS|SUSPICIOUS|BENIGN)\b")

# Banner tints per overall severity/posture (bg, border+text).
_BANNER_STYLES = {
    "malicious": ("#ffebe9", "#cf222e"),
    "escalated": ("#ffebe9", "#cf222e"),
    "suspicious": ("#fff8c5", "#9a6700"),
    "mixed": ("#fff8c5", "#9a6700"),
    "benign": ("#dafbe1", "#1a7f37"),
    "stable": ("#dafbe1", "#1a7f37"),
    "de-escalated": ("#dafbe1", "#1a7f37"),
}


def _colorize_words(text):
    """Wrap severity words in colored spans. Input is already-escaped
    HTML text; word boundaries keep benign_anomaly untouched ('_' is a
    word char, so there is no boundary before it)."""
    return _SEVERITY_RE.sub(
        lambda m: (f'<span style="color:{_SEVERITY_COLORS[m.group(1)]}">'
                   f'{m.group(1)}</span>'),
        text)


def _inline(text):
    """Escape, then re-apply the inline markup the report uses.

    Italics need two distinct treatments: *asterisk* pairs are safe as
    a plain regex (the reports never use bare asterisks otherwise), but
    _underscore_ pairs are only honored when they wrap the WHOLE
    segment - snake_case identifiers (benign_anomaly, unique_dsts) and
    paths inside <code> would otherwise shear mid-word."""
    out = _escape(text)
    s = out.strip()
    whole_em = (len(s) > 2 and s.startswith("_") and s.endswith("_")
                and not s.startswith("__"))
    if whole_em:
        out = s[1:-1]
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<!\*)\*([^*\s][^*]*)\*(?!\*)", r"<em>\1</em>", out)
    # Severity words inside BOLD spans become colored chips (prose
    # mentions stay plain - coloring every occurrence reads as noise).
    out = re.sub(r"<strong>([^<]+)</strong>",
                 lambda m: f"<strong>{_colorize_words(m.group(1))}</strong>",
                 out)
    if whole_em:
        out = f"<em style='color:#57606a'>{out}</em>"
    return out


def _split_row(line):
    cells = line.strip().strip("|").split("|")
    return [c.strip() for c in cells]


def _render_cell(c):
    """One table cell: inline markup plus a color when the whole cell is
    a bare severity word (flip tables carry them unbolded)."""
    rendered = _inline(c)
    color = _SEVERITY_COLORS.get(c.strip())
    if color and "<" not in rendered:
        return f'<span style="color:{color}">{rendered}</span>'
    return rendered


def markdown_to_html(md, banner=None):
    """Render the verdict report as standalone HTML for an email body.

    banner: optional {"severity": word, "text": str} rendered as a
    color-tinted strip at the very top - the report's verdict box. The
    severity picks the tint (malicious/escalated red, suspicious/mixed
    amber, benign/stable green); unknown words get a neutral grey.
    """
    html = []
    in_table = False
    in_list = False
    td_row = 0

    def close_blocks():
        nonlocal in_table, in_list
        if in_table:
            html.append("</table>")
            in_table = False
        if in_list:
            html.append("</ul>")
            in_list = False

    for raw in (md or "").splitlines():
        line = raw.rstrip()
        stripped = line.strip()

        if not stripped:
            close_blocks()
            continue

        # A separator row (|---|---|) only shapes the table above it.
        if in_table and set(stripped) <= set("|-: "):
            continue

        if stripped.startswith("|") and stripped.endswith("|"):
            cells = _split_row(stripped)
            if not in_table:
                close_blocks()
                html.append('<table cellspacing="0" cellpadding="6" '
                            'style="border-collapse:collapse;'
                            'border:1px solid #d0d7de;font-size:13px">')
                in_table = True
                td_row = 0
                tag, extra = "th", (
                    'style="background:#f6f8fa;text-align:left;'
                    'border:1px solid #d0d7de"')
                tr_style = ""
            else:
                tag, extra = "td", 'style="border:1px solid #d0d7de"'
                td_row += 1
                # zebra striping - readability on the wide vote tables
                tr_style = (' style="background:#fafbfc"'
                            if td_row % 2 == 0 else "")
            row = "".join(f"<{tag} {extra}>{_render_cell(c)}</{tag}>"
                          for c in cells)
            html.append(f"<tr{tr_style}>{row}</tr>")
            continue

        close_blocks()

        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            level = min(max(level, 1), 4)
            body = _inline(stripped[level:].strip())
            # h2 gets a hairline underline - it is the section separator
            # in a report that is mostly tables.
            rule = ("border-bottom:1px solid #d8dee4;padding-bottom:4px;"
                    if level == 2 else "")
            html.append(f"<h{level} style='margin:18px 0 8px;{rule}'>"
                        f"{body}</h{level}>")
            continue

        if stripped.startswith(">"):
            body = _inline(stripped.lstrip("> ").strip())
            html.append(
                "<blockquote style='margin:8px 0;padding:8px 12px;"
                "border-left:3px solid #d0d7de;background:#f6f8fa;"
                f"color:#57606a'>{body}</blockquote>")
            continue

        if stripped.startswith(("- ", "* ")):
            if not in_list:
                html.append("<ul style='margin:8px 0 8px 18px;padding:0'>")
                in_list = True
            html.append(f"<li>{_inline(stripped[2:])}</li>")
            continue

        if set(stripped) <= set("-*_") and len(stripped) >= 3:
            html.append("<hr style='border:0;border-top:1px solid #d0d7de'>")
            continue

        html.append(f"<p style='margin:8px 0'>{_inline(stripped)}</p>")

    close_blocks()
    banner_html = ""
    if isinstance(banner, dict) and banner.get("text"):
        sev = str(banner.get("severity") or "").lower()
        bg, fg = _BANNER_STYLES.get(sev, ("#f6f8fa", "#57606a"))
        banner_html = (
            f'<div style="background:{bg};border:1px solid {fg};'
            f'border-radius:8px;padding:12px 16px;margin:0 0 16px;'
            f'color:{fg};font-weight:600;font-size:15px">'
            f'{_escape(str(banner["text"]))}</div>')
    body = "\n".join(html)
    # The charset declaration has to travel INSIDE the document. As an
    # email body the MIME part carries charset=utf-8, but the same HTML
    # is also written to disk and served by the ingest API as a bare
    # `text/html` with no charset parameter - a browser then falls back
    # to its locale default (windows-1252 on a Western Windows) and the
    # report's non-ASCII characters (the scales glyph on a split panel,
    # the ellipsis, any Unicode in a hostname) render as mojibake.
    # Item 10 (v0.6.0): print CSS for the PDF path. weasyprint honours
    # @page + page-break-* rules; email clients ignore them. Rules:
    # - h2 (section headers) starts a new page.
    # - tables never split a row across pages (page-break-inside:
    #   avoid on tr).
    # - tables repeat their <thead> on each page (native HTML behaviour
    #   as long as thead exists, which markdown_to_html emits).
    print_css = (
        "@page { size: A4; margin: 14mm 12mm 16mm 12mm; }"
        " h2 { page-break-before: always; }"
        " h2:first-of-type { page-break-before: avoid; }"
        " tr, li, blockquote { page-break-inside: avoid; }"
        " table { page-break-inside: auto; }"
        " thead { display: table-header-group; }"
    )
    return (
        "<html><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,"
        "initial-scale=1\">"
        f"<style>{print_css}</style></head>"
        "<body style=\"font-family:-apple-system,Segoe UI,Helvetica,"
        "Arial,sans-serif;color:#1f2328;line-height:1.5;max-width:820px\">"
        f"{banner_html}{body}"
        "</body></html>")


_ATTACHMENT_MIME = {
    ".pdf":  ("application", "pdf"),
    ".html": ("text",        "html"),
    ".htm":  ("text",        "html"),
    ".json": ("application", "json"),
    ".md":   ("text",        "markdown"),
    ".txt":  ("text",        "plain"),
    ".csv":  ("text",        "csv"),
    ".xml":  ("application", "xml"),
}


def _attachment_mime(name):
    """Pick a sensible (maintype, subtype) from the filename extension.
    Unknown extensions fall back to a generic binary type so a mail
    client offers a Download instead of guessing wrongly."""
    ext = os.path.splitext(name)[1].lower()
    return _ATTACHMENT_MIME.get(ext, ("application", "octet-stream"))


def build_message(to_addr, subject, markdown_body, sender,
                  attachments=None):
    """Build a multipart/alternative message with the markdown as the
    plain-text part and the rendered HTML as the rich part. Attachments
    are typed by extension - PDF stays application/pdf, HTML stays
    text/html - so mail clients open them the right way instead of
    treating everything as JSON."""
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to_addr
    msg.set_content(markdown_body)
    msg.add_alternative(markdown_to_html(markdown_body), subtype="html")
    for name, data in (attachments or {}).items():
        if isinstance(data, str):
            data = data.encode("utf-8")
        maintype, subtype = _attachment_mime(name)
        msg.add_attachment(data, maintype=maintype, subtype=subtype,
                           filename=name)
    return msg


def send_report(to_addr, markdown_body, subject=None, attachments=None,
                env=None, smtp_factory=None):
    """Send the report. Returns (ok, message); never raises.

    smtp_factory exists for tests: it receives (host, port) and returns
    an object with the smtplib.SMTP interface.
    """
    if not valid_address(to_addr):
        return False, f"invalid email address: {to_addr!r}"
    try:
        cfg = smtp_settings(env)
    except SMTPConfigError as e:
        return False, str(e)

    subject = subject or "NetSec Judge verdicts"
    try:
        msg = build_message(to_addr.strip(), subject, markdown_body,
                            cfg["sender"], attachments)
    except Exception as e:
        return False, f"could not build the message: {type(e).__name__}: {e}"

    try:
        if smtp_factory is not None:
            server = smtp_factory(cfg["host"], cfg["port"])
            with server:
                server.login(cfg["user"], cfg["password"])
                server.send_message(msg)
        elif cfg["port"] == 465:
            ctx = ssl.create_default_context()
            with smtplib.SMTP_SSL(cfg["host"], cfg["port"], timeout=30,
                                  context=ctx) as server:
                server.login(cfg["user"], cfg["password"])
                server.send_message(msg)
        else:
            with smtplib.SMTP(cfg["host"], cfg["port"], timeout=30) as server:
                server.starttls(context=ssl.create_default_context())
                server.login(cfg["user"], cfg["password"])
                server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        return False, (f"SMTP authentication failed ({e.smtp_code}). For "
                       "Gmail, SMTP_PASS must be an app password, not the "
                       "account password.")
    except Exception as e:
        return False, f"SMTP send failed: {type(e).__name__}: {e}"
    return True, f"report sent to {to_addr}"


def main(argv=None):
    """CLI: send an existing markdown report.

    usage: python llm_judge/send_report.py <report.md> <address>
                                           [--subject S] [--json verdicts.json]
    """
    import argparse

    ap = argparse.ArgumentParser(
        description="Email a judge verdict report (SMTP settings come from "
                    "the environment)")
    ap.add_argument("report", help="Path to the markdown report")
    ap.add_argument("address", help="Recipient email address")
    ap.add_argument("--subject", default=None)
    ap.add_argument("--json", default=None,
                    help="Optional verdicts.json to attach")
    args = ap.parse_args(argv)

    with open(args.report, encoding="utf-8") as f:
        body = f.read()
    attachments = {}
    if args.json and os.path.isfile(args.json):
        with open(args.json, encoding="utf-8") as f:
            attachments[os.path.basename(args.json)] = f.read()

    ok, message = send_report(args.address, body, subject=args.subject,
                              attachments=attachments)
    print(f"[send_report] {message}", flush=True)
    return 0 if ok else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
